### ISSUE TITLE
Problem when writing spectrum attribute with empty list

### ISSUE THREAD

**Issue by reszelaz** [tango-controls/pytango#159]
I use PyTango 9.2.0 and tango 9.2.5 (default Debian 9 packages).
I have a problem when I try to write an empty list to a spectrum attribute in a [python device](https://github.com/tango-controls/pytango/files/1281394/PyDsExp.txt) (sorry about the old API...).
```
In [21]: pydsexp = PyTango.DeviceProxy("test/pydsexp/1")

In [22]: pydsexp.write_attribute("attr1", [])

In [23]: pydsexp.read_attribute("attr1")
---------------------------------------------------------------------------
DevFailed                                 Traceback (most recent call last)
<ipython-input-23-4a01a2a2ea48> in <module>()
----> 1 pydsexp.read_attribute("attr1")

/usr/lib/python2.7/dist-packages/tango/green.pyc in greener(self, *args, **kwargs)
    264 
    265         # submit the method
--> 266         ret = submitter(fn, self, *args, **kwargs)
    267 
    268         # return the proper result

/usr/lib/python2.7/dist-packages/tango/green.pyc in submit(self, fn, *args, **kwargs)
     98 class SynchExecutor(object):
     99     def submit(self, fn, *args, **kwargs):
--> 100         return fn(*args, **kwargs)
    101 
    102 __synch_executor = SynchExecutor()

/usr/lib/python2.7/dist-packages/tango/device_proxy.pyc in __DeviceProxy__read_attribute(self, value, extract_as)
    328 
    329 def __DeviceProxy__read_attribute(self, value, extract_as=ExtractAs.Numpy):
--> 330     return __check_read_attribute(self._read_attribute(value, extract_as))
    331 
    332 #def __DeviceProxy__read_attribute(self, value, extract_as=ExtractAs.Numpy,

/usr/lib/python2.7/dist-packages/tango/device_proxy.pyc in __check_read_attribute(dev_attr)
    123 def __check_read_attribute(dev_attr):
    124     if dev_attr.has_failed:
--> 125         raise DevFailed(*dev_attr.get_err_stack())
    126     return dev_attr
    127 

DevFailed: DevFailed[
DevError[
    desc = Data pointer for attribute attr1 is NULL!
  origin = Attribute::set_value()
  reason = API_AttrOptProp
severity = ERR]

DevError[
    desc = Failed to read_attribute on device test/pydsexp/1, attribute attr1
  origin = DeviceProxy::read_attribute()
  reason = API_AttributeFailed
severity = ERR]
]
```
When I do the same test in the TangoTest attribute e.g. float_spectrum I don't see this problem:
```
In [24]: tangotest = PyTango.DeviceProxy("sys/tg_test/1")

In [25]: tangotest.write_attribute("float_spectrum", [])

In [26]: tangotest.read_attribute("float_spectrum")
Out[26]: DeviceAttribute(data_format = tango._tango.AttrDataFormat.SPECTRUM, dim_x = 0, dim_y = 0, has_failed = False, is_empty = True, name = 'float_spectrum', nb_read = 0, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 0, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1504707208, tv_usec = 447424), type = tango._tango.CmdArgType(4294967295), value = None, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None)
```
Any suggestion? Am I doing something wrong in the server or it may be a bug?

**Comment by vxgmichel** [comment]
Thanks for your report!

I tried to reproduce it and it does not happen with pytango-9.2.2, tango-9.2.2 and the following device:

```python
from tango import AttrWriteType
from tango.server import Device, attribute

class Test(Device):

    value = [1, 2, 3]

    @attribute(
        dtype=(float,),
        max_dim_x=10,
        access=AttrWriteType.READ_WRITE)
    def test(self):
        return self.value

    @test.write
    def test(self, value):
        self.value = value
```
Running the server:
```console
$ python -m tango.test_context test.Test
Ready to accept request
Test started on port 8888 with properties {}
Device access: tango://pcvimichel:8888/test/nodb/test#dbase=no
Server access: tango://pcvimichel:8888/dserver/Test/test#dbase=no
```
Testing:
```console
$ itango3
ITango 9.2.2 -- An interactive Tango client.
Running on top of Python 3.5.4, IPython 6.1 and PyTango 9.2.2

In [1]: d = Device('tango://pcvimichel:8888/test/nodb/test#dbase=no')

In [2]: d
Out[2]: Test(test/nodb/test)

In [3]: d.test
Out[3]: array([ 1.,  2.,  3.])

In [4]: d.write_attribute('test', [])
```

I did notice a problem on the client side though, the result is `Ǹone` when reading the attribute:

```console
In [25]: d.test is None
Out[25]: True
```

**Comment by vxgmichel** [comment]
I tried again and it does not happen with pytango-9.2.2, tango-9.2.5a and the device above.

**Comment by reszelaz** [comment]
Yes, with a device from Sardana, on the client side the result was also `None`. If it is fixed in the latest release I think that this issue can be closed. We can apply a workaround. Thanks!

**Comment by jkotan** [comment]
Hi @vxgmichel  and @reszelaz ,

Is this but fixed? I get it by running my tests with py3. I use debian9 with tango-9.2.5a and pytango-9.2.5.dev0 

I can easily reproduce for py2 and py3 it with the following server:
```python

import PyTango
import sys

class NMacroServer(PyTango.Device_4Impl):

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self, cl, name)
        NMacroServer.init_device(self)

    def init_device(self):
        self.set_state(PyTango.DevState.ON)
        self.get_device_properties(self.get_device_class())
        self.attr_DoorList = ['doortestp09/testts/t1r228']

    def read_DoorList(self, attr):
        attr.set_value(self.attr_DoorList)

    def write_DoorList(self, attr):
        self.attr_DoorList = attr.get_write_value()


class NMacroServerClass(PyTango.DeviceClass):

    attr_list = {
        'DoorList':
            [[PyTango.DevString,
              PyTango.SPECTRUM,
              PyTango.READ_WRITE,
              256],
             {
                 'description': "Door List",
            }],
    }

    def __init__(self, name):
        PyTango.DeviceClass.__init__(self, name)
        self.set_type(name)


if __name__ == '__main__':
    try:
        argv = list(sys.argv)
        argv[0] = "NMacroServer"
        py = PyTango.Util(argv)
        py.add_class(NMacroServerClass, NMacroServer)

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print('-------> Received a DevFailed exception: %s' % e)
    except Exception as e:
        print('-------> An unforeseen exception occured.... %s' % e)
```

The following test

```python
import PyTango
dp = PyTango.DeviceProxy("test/nm/t1")
dl = dp.DoorList
dp.DoorList = []
dl2 = dp.DoorList
```

gives

    Traceback (most recent call last):
      File "lrun.py", line 5, in <module>
	dl2 = dp.DoorList
      File "/home/jkotan/testinst/lib/python2.7/site-packages/pytango-9.2.5.dev0-py2.7-linux-x86_64.egg/tango/device_proxy.py", line 269, in __DeviceProxy__getattr
	return __get_attribute_value(self, attr_info, name)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/pytango-9.2.5.dev0-py2.7-linux-x86_64.egg/tango/device_proxy.py", line 247, in __get_attribute_value
	attr_value = self.read_attribute(name).value
      File "/home/jkotan/testinst/lib/python2.7/site-packages/pytango-9.2.5.dev0-py2.7-linux-x86_64.egg/tango/green.py", line 195, in greener
	return executor.run(fn, args, kwargs, wait=wait, timeout=timeout)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/pytango-9.2.5.dev0-py2.7-linux-x86_64.egg/tango/green.py", line 109, in run
	return fn(*args, **kwargs)
      File "/home/jkotan/testinst/lib/python2.7/site-packages/pytango-9.2.5.dev0-py2.7-linux-x86_64.egg/tango/device_proxy.py", line 379, in __DeviceProxy__read_attribute
	return __check_read_attribute(self._read_attribute(value, extract_as))
      File "/home/jkotan/testinst/lib/python2.7/site-packages/pytango-9.2.5.dev0-py2.7-linux-x86_64.egg/tango/device_proxy.py", line 121, in __check_read_attribute
	raise DevFailed(*dev_attr.get_err_stack())
    PyTango.DevFailed: DevFailed[
    DevError[
	desc = Data pointer for attribute DoorList is NULL!
      origin = Attribute::set_value()
      reason = API_AttrOptProp
    severity = ERR]

    DevError[
	desc = Failed to read_attribute on device test/nm/t1, attribute DoorList
      origin = DeviceProxy::read_attribute()
      reason = API_AttributeFailed
    severity = ERR]
    ]

**Comment by jkotan** [comment]
It looks like the following patch fixes my server

```diff
	 def __init__(self, cl, name):
	     PyTango.Device_4Impl.__init__(self, cl, name)
	     NMacroServer.init_device(self)
    +        self.attr_DoorList = ['doortestp09/testts/t1r228']

	 def init_device(self):
	     self.set_state(PyTango.DevState.ON)
    @@ -14,7 +15,7 @@ class NMacroServer(PyTango.Device_4Impl):
	     self.attr_DoorList = ['doortestp09/testts/t1r228']

	 def read_DoorList(self, attr):
    -        attr.set_value(self.attr_DoorList)
    +        attr.set_value(self.attr_DoorList or [])

	 def write_DoorList(self, attr):
	     self.attr_DoorList = attr.get_write_value()

```

**Comment by vxgmichel** [comment]
Hi all, 

The reason why I couldn't reproduce the issue in the first place is because I used an array of float instead of an array of string. Sorry about that, I created a new dedicated issue for more clarity: #229.

**Comment by vxgmichel** [comment]
I also created the related issue: #230
