### ISSUE TITLE
[python 3.7] ModuleNotFoundError: No module named 'mock'

### ISSUE THREAD

**Issue by picca** [tango-controls/pytango#203]
Still looking at the Debain python 3.7 transition.

I get this error during the documentation build.

Cheers

Frederic

```
The HTML pages are in build/html.
I: pybuild base:217: PYTHONPATH=/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_tango/build python3.7 -m sphinx -N -bhtml doc build/html
Running Sphinx v1.7.5

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "conf.py", line 25, in <module>
    import tango
  File "/<<PKGBUILDDIR>>/tango/__init__.py", line 137, in <module>
    from ._tango import (
ModuleNotFoundError: No module named 'tango._tango'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 27, in <module>
    from mock_tango_extension import tango
  File "/<<PKGBUILDDIR>>/doc/mock_tango_extension.py", line 28, in <module>
    from mock import MagicMock
ModuleNotFoundError: No module named 'mock'
```

**Comment by vxgmichel** [comment]
The doc requirements are listed in [doc/environment.yml](https://github.com/tango-controls/pytango/blob/develop/doc/environment.yml):

- python=3.5
- numpy
- gevent
- graphviz
- mock
- pillow
- sphinx
- sphinx_rtd_theme

The documentation is built by [readthedocs](http://readthedocs.org/projects/pytango/builds/).
