### ISSUE TITLE
Expecting a sequence!

### ISSUE THREAD

**Issue by jkotan** [tango-controls/pytango#210]
When I try to call a tango command which takes as an argument a list of strings `dependentComponents(...)` 
on debian 9 with python3.5 and pytango from the `develop` branch I get the following error

    Traceback (most recent call last):
      File "/home/jkotan/ndts/nexdatas.configserver/test/XMLConfiguratorTest.py", line 6458, in test_dependentComponents_man
	mdss = el.dependentComponents(css)
      File "/home/jkotan/testinst3/lib/python3.5/site-packages/PyTango/device_proxy.py", line 194, in f
	return dp.command_inout(name, *args, **kwds)
      File "/home/jkotan/testinst3/lib/python3.5/site-packages/PyTango/green.py", line 173, in greener
	ret = submit(fn, self, *args, **kwargs)
      File "/home/jkotan/testinst3/lib/python3.5/site-packages/PyTango/green.py", line 83, in synch_submit
	return get_synch_executor().submit(fn, *args, **kwargs)
      File "/home/jkotan/testinst3/lib/python3.5/site-packages/PyTango/green.py", line 75, in submit
	return fn(*args, **kwargs)
      File "/home/jkotan/testinst3/lib/python3.5/site-packages/PyTango/connection.py", line 101, in __Connection__command_inout
	r = Connection.command_inout_raw(self, name, *args, **kwds)
      File "/home/jkotan/testinst3/lib/python3.5/site-packages/PyTango/connection.py", line 127, in __Connection__command_inout_raw
	return self.__command_inout(cmd_name, param)
    PyTango.DevFailed: DevFailed[
    DevError[
	desc = Expecting a sequence!
      origin = insert_array()
      reason = PyDs_WrongParameters
    severity = ERR]

    DevError[
	desc = Failed to execute command_inout on device testp09/testmcs/testr228, command dependentComponents
      origin = Connection::command_inout()
      reason = API_CommandFailed
    severity = ERR]
    ]

I pass a python list into the command.  It fails  even with an empty list. 
But the error does not always appear, e.g. on my local machine it fails while tests on travis work OK.

Do you know any idea by what this error can be caused?

**Comment by jkotan** [comment]
This problem appears only for python3. For python2 it works fine.

**Comment by vxgmichel** [comment]
Hi @jkotan,

I could not reproduce your issue using the following server code:

```python
from tango import server

class Test(server.Device):

    @server.command(dtype_in=(str,), dtype_out=(str,))
    def lower(self, arg):
        return list(map(str.lower, arg))
```
Running the server:
```bash
$ python -m tango.test_context server.Test
Ready to accept request
Test started on port 8888 with properties {}
Device access: tango://pcvimichel:8888/test/nodb/test#dbase=no
Server access: tango://pcvimichel:8888/dserver/Test/test#dbase=no
```
Running the command:
```python
ITango 9.2.4 -- An interactive Tango client.
Running on top of Python 3.5.5, IPython 6.5 and PyTango 9.2.4
In [1]: d = Device('tango://pcvimichel:8888/test/nodb/test#dbase=no')
In [2]: d.lower(['AAAA', 'BBBB'])
Out[2]: ['aaaa', 'bbbb']
```
So the issue is probably about the return value of the command.

Could you provide the command implementation?

**Comment by jkotan** [comment]
Hi Vincent,

Many Thanks. Indeed.  I forgot to change `keys()` to a list.
