### ISSUE TITLE
Propagating exception from C is broken in python 3

### ISSUE THREAD

**Issue by vxgmichel** [tango-controls/pytango#215]
Example (`test.py`):

```python
from tango.server import Device, attribute, command


class Test(Device):

    @attribute
    def attr(self):
        1/0

    @command
    def cmd(self):
        1/0
```

Note: the problem does not occur if `1/0` is replaced with `raise ZeroDivisionError('bla')`

Using python 2:
```console
$ python -m tango.test_context test.Test
Can't create notifd event supplier. Notifd event not available
Ready to accept request
Test started on port 8888 with properties {}
Device access: tango://pcvimichel:8888/test/nodb/test#dbase=no
Server access: tango://pcvimichel:8888/dserver/Test/test#dbase=no
```
```python
>>> d = DeviceProxy('tango://pcvimichel:8888/test/nodb/test#dbase=no')
>>> d.attr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tango/device_proxy.py", line 290, in __DeviceProxy__getattr
    return __get_attribute_value(self, attr_info, name)
  File "tango/device_proxy.py", line 247, in __get_attribute_value
    attr_value = self.read_attribute(name).value
  File "tango/green.py", line 195, in greener
    return executor.run(fn, args, kwargs, wait=wait, timeout=timeout)
  File "tango/green.py", line 109, in run
    return fn(*args, **kwargs)
  File "tango/device_proxy.py", line 379, in __DeviceProxy__read_attribute
    return __check_read_attribute(self._read_attribute(value, extract_as))
  File "tango/device_proxy.py", line 121, in __check_read_attribute
    raise DevFailed(*dev_attr.get_err_stack())
PyTango.DevFailed: DevFailed[
DevError[
    desc = ZeroDivisionError: integer division or modulo by zero
           
  origin =   File "/home/vimiche/miniconda/envs/bliss/lib/python2.7/site-packages/tango/server.py", line 132, in read_attr
    ret = worker.execute(read_method, self)
  File "/home/vimiche/miniconda/envs/bliss/lib/python2.7/site-packages/tango/green.py", line 98, in execute
    return fn(*args, **kwargs)
  File "test.py", line 10, in attr
    1/0

  reason = PyDs_PythonError
severity = ERR]

DevError[
    desc = Failed to read_attribute on device test/nodb/test, attribute attr
  origin = DeviceProxy::read_attribute()
  reason = API_AttributeFailed
severity = ERR]
]
>>> d.cmd()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tango/device_proxy.py", line 239, in f
    return dp.command_inout(name, *args, **kwds)
  File "tango/green.py", line 195, in greener
    return executor.run(fn, args, kwargs, wait=wait, timeout=timeout)
  File "tango/green.py", line 109, in run
    return fn(*args, **kwargs)
  File "tango/connection.py", line 104, in __Connection__command_inout
    r = Connection.command_inout_raw(self, name, *args, **kwds)
  File "tango/connection.py", line 133, in __Connection__command_inout_raw
    return self.__command_inout(cmd_name, param)
PyTango.DevFailed: DevFailed[
DevError[
    desc = ZeroDivisionError: integer division or modulo by zero
           
  origin =   File "/home/vimiche/miniconda/envs/bliss/lib/python2.7/site-packages/tango/server.py", line 1138, in cmd
    return get_worker().execute(f, self, *args, **kwargs)
  File "/home/vimiche/miniconda/envs/bliss/lib/python2.7/site-packages/tango/green.py", line 98, in execute
    return fn(*args, **kwargs)
  File "test.py", line 19, in cmd
    1/0

  reason = PyDs_PythonError
severity = ERR]

DevError[
    desc = Failed to execute command_inout on device test/nodb/test, command cmd
  origin = Connection::command_inout()
  reason = API_CommandFailedseverity = ERR]
]
>>>
```

Using python 3:
```
$ python -m tango.test_context test.Test
Can't create notifd event supplier. Notifd event not available
Ready to accept request
Test started on port 8888 with properties {}
Device access: tango://pcvimichel:8888/test/nodb/test#dbase=no
Server access: tango://pcvimichel:8888/dserver/Test/test#dbase=no
```
```python
>>> from tango import DeviceProxy
>>> d = DeviceProxy('tango://pcvimichel:8888/test/nodb/test#dbase=no')
>>> d.attr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vimiche/pytango/tango/device_proxy.py", line 290, in __DeviceProxy__getattr
    return __get_attribute_value(self, attr_info, name)
  File "/home/vimiche/pytango/tango/device_proxy.py", line 247, in __get_attribute_value
    attr_value = self.read_attribute(name).value
  File "/home/vimiche/pytango/tango/green.py", line 195, in greener
    return executor.run(fn, args, kwargs, wait=wait, timeout=timeout)
  File "/home/vimiche/pytango/tango/green.py", line 109, in run
    return fn(*args, **kwargs)
  File "/home/vimiche/pytango/tango/device_proxy.py", line 379, in __DeviceProxy__read_attribute
    return __check_read_attribute(self._read_attribute(value, extract_as))
  File "/home/vimiche/pytango/tango/device_proxy.py", line 121, in __check_read_attribute
    raise DevFailed(*dev_attr.get_err_stack())
PyTango.DevFailed: DevFailed[
DevError[
    desc = Unforseen exception when trying to read attribute. It was even not a Tango DevFailed exception
  origin = Device_3Impl::read_attributes_no_except
  reason = API_CorbaSysException 
severity = ERR]

DevError[
    desc = Failed to read_attribute on device test/nodb/test, attribute attr
  origin = DeviceProxy::read_attribute()
  reason = API_AttributeFailed
severity = ERR]
]
>>> d.cmd()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vimiche/pytango/tango/device_proxy.py", line 239, in f
    return dp.command_inout(name, *args, **kwds)
  File "/home/vimiche/pytango/tango/green.py", line 195, in greener
    return executor.run(fn, args, kwargs, wait=wait, timeout=timeout)
  File "/home/vimiche/pytango/tango/green.py", line 109, in run
    return fn(*args, **kwargs)
  File "/home/vimiche/pytango/tango/connection.py", line 104, in __Connection__command_inout
    r = Connection.command_inout_raw(self, name, *args, **kwds)
  File "/home/vimiche/pytango/tango/connection.py", line 133, in __Connection__command_inout_raw
    return self.__command_inout(cmd_name, param)
PyTango.CommunicationFailed: DevFailed[
DevError[
    desc = UNKNOWN CORBA system exception
  origin = Connection::command_inout()
  reason = API_CorbaException
severity = ERR]

DevError[
    desc = Failed to execute command_inout on device test/nodb/test, command cmd
  origin = Connection::command_inout()
  reason = API_CommunicationFailed
severity = ERR]
]
```

We also need tests against this kind of regression.

**Comment by vxgmichel** [comment]
Fixed! (PR #225)
