### ISSUE TITLE
Catching classes that do not inherit from BaseException is not allowed python3

### ISSUE THREAD

**Issue by jkotan** [tango-controls/pytango#223]
Hi,

It looks like pytango exception does not inherent from BaseException which is not allowed in python3, e.g.

```python
    import PyTango
    try:
        ob = object
        ob.State()
    except (PyTango.DevFailed, PyTango.Except, PyTango.DevError):
        pass
    except AttributeError:
        pass
```

gives:

```python
    Traceback (most recent call last):
      File "test.py", line 5, in <module>
	ob.State()
    AttributeError: type object 'object' has no attribute 'State'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "test.py", line 6, in <module>
	except (PyTango.DevFailed, PyTango.Except, PyTango.DevError):
    TypeError: catching classes that do not inherit from BaseException is not allowed
 ```
while 
```python
    import PyTango
    try:
        ob = object
        ob.State()
    except AttributeError:
        pass
    except (PyTango.DevFailed, PyTango.Except, PyTango.DevError):
        pass
```
works fine.

It may be related to #215

**Comment by vxgmichel** [comment]
Hi @jkotan,

Well, it doesn't really make sense to catch a non-exception, since it is not possible to raise a non-exception:
```python
>>> raise 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must derive from BaseException
```
So my suggestion is to simply use:

```python
except tango.DevFailed:
        pass
```

**Comment by jkotan** [comment]
Thanks. It works.
