### ISSUE TITLE
AttributeProxy.poll() throws ArgumentError

### ISSUE THREAD

**Issue by sdebionne** [tango-controls/pytango#224]
With Python 2.7.15 (on Windows)

```python
>>> tango.__version_info__
(9, 2, 4)
```

```python
>>> att = AttributeProxy(“tango/tangotest/1/long_scalar”)
>>> att.poll()
att.poll()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/debionne/miniconda3/envs/simu-py2/lib/python2.7/site-packages/tango/attribute_proxy.py", line 333, in __new_fn
    return getattr(self._AttributeProxy__dev_proxy, dp_fn_name)(self.name(), *args, **kwds)
Boost.Python.ArgumentError: Python argument types in
    DeviceProxy.poll_attribute(DeviceProxy, str)
did not match C++ signature:
    poll_attribute(Tango::DeviceProxy {lvalue} self, char const* attr_name, int period)
>>> type(att.name())
<type 'str'>
```

**Comment by sdebionne** [comment]
My bad, poll take a `period` argument. Maybe the doc could mention the actual parameters rather than `(*args, **kwds)`?
