### ISSUE TITLE
[python 2.7] ImportError: No module named mock

### ISSUE THREAD

**Issue by jkotan** [tango-controls/pytango#244]
When I try to build documentation on python2.7 I get the following error:
```
running build_doc
creating /build/pytango-9.2.5/build/sphinx
creating /build/pytango-9.2.5/build/sphinx/doctrees
creating /build/pytango-9.2.5/build/sphinx/html
Running Sphinx v1.4.9
Traceback (most recent call last):
  File "setup.py", line 575, in <module>
    main()
  File "setup.py", line 571, in main
    return setup(**setup_args())
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 204, in run
    dftbuild.run(self)
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 284, in run
    sphinx.setup_command.BuildDoc.run(self)
  File "/usr/lib/python2.7/dist-packages/sphinx/setup_command.py", line 161, in run
    freshenv=self.fresh_env)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 137, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 287, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 130, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/dist-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 27, in <module>
    from mock_tango_extension import tango
  File "/build/pytango-9.2.5/doc/mock_tango_extension.py", line 28, in <module>
    from unittest.mock import MagicMock
ImportError: No module named mock
E: pybuild pybuild:283: build: plugin distutils failed with: exit code=1: /usr/bin/python setup.py build 
dh_auto_build: pybuild --build -i python{version} -p 2.7 returned exit code 13
debian/rules:10: recipe for target 'build' failed
```
The following patch
```patch
diff --git a/doc/mock_tango_extension.py b/doc/mock_tango_extension.py
index 6197d2b..adee4fa 100644
--- a/doc/mock_tango_extension.py
+++ b/doc/mock_tango_extension.py
@@ -25,7 +25,10 @@ version older than 3.5 (failed with 2.7 and 3.4)
 
 # Imports
 import sys
-from unittest.mock import MagicMock
+try:
+    from unittest.mock import MagicMock
+except ImportError:
+    from mock import MagicMock
 
 __all__ = ('tango',)

```

fixes the issue and it is compatible with py2.7 and py > 3.3 (i.e. #203 )

**Comment by vxgmichel** [comment]
Hi @jkotan, 

Python >= 3.5 is [a requirement](https://github.com/tango-controls/pytango/blob/ef4b465b71106beaec38c90db2dadee1fa3701dd/doc/mock_tango_extension.py#L22-L23) for building the documentation. I guess we should add an extra check for that:

```python
if sys.version_info < (3, 5):
    raise RuntimeError("Mocking the _tango extension requires python >= 3.5")
```

**Comment by hardion** [comment]
I can make a quick PR to limit python version.

**Comment by tiagocoutinho** [comment]
That would be great @hardion!

**Comment by aureocarneiro** [comment]
Hey @hardion can I do the PR or you are working on that ?
